services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: baszik-back
    container_name: baszik_back
    ports:
      - "5000:5000"
    restart: unless-stopped
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: baszik-front
    container_name: baszik_front
    ports:
      - "5173:5173"
    environment:
      - VITE_PORT=5173
    restart: unless-stopped